name: Update
on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup dependencies
      run: |
        npm ci --production
    - name: Run extract-data.js
      run: node extract-data.js
    - name: Commit changes
      run: |
        git config user.name "w3c-update-bot"
        git config user.email "<>"
        git add -u
        git commit -m "Update automatically data files"
        git show
    - name: Push changes
      if: github.ref == 'refs/heads/master' && github.event.commits[0].author.name != 'w3c-update-bot'
      run: |
        git remote set-url --push origin https://x-access-token:${{ GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git push origin HEAD:master
